### ISSUE TITLE
fix(admin-builder): searching with no location causes empty result

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/wp-business-reviews#128] opened 2018-04-27 21:54 UTC
## User Story

As an `admin` when I type `tacos` and hit the `enter` key I receive:

![2018-04-27_14-51-45](https://user-images.githubusercontent.com/1571635/39386710-b56a584c-4a2a-11e8-8468-aa6411d82a74.gif)

I expect the system to validate my mistakes so that I can progress through the builder quickly using the my keyboard `tab` and `enter` keys.

**Comment by kevinwhoffman** [comment] 2018-04-27 21:56
Thanks, already on it. Duplicate of #126.

**Closed by kevinwhoffman** 2018-04-27 21:56 UTC
