### ISSUE TITLE
Ensure collection appears correctly for older version of mac and safari

### ISSUE THREAD

**Issue by marutim** [WordImpress/wp-business-reviews#256] opened 2018-09-11 11:34 UTC
## Current Behavior
The collections do not appear at all for the older version of mac and Safari.

I tested this in browser stack and could only make the collections work for the combination of Mac ( High Sierra ) + Safari 11.1 which is the latest, anything below than that does not work. I tested it in browser stack after a HS ticket, where the user is having the issue seeing the collections in Yosemite ( Mac Os ) + safari

I found the collection working fine for browsers like Chrome and Firefox with the older versions of Mac OS.

## Expected Behavior
Collections should appear correctly in older versions of Mac Os and safari.

## Steps to Reproduce
Check the collections in the older versions of Mac Os and Safari. I tested it in Browserstack.

## Related
HS link: https://secure.helpscout.net/conversation/653504615/24515?folderId=2231395

## Acceptance Criteria
- [ ] Collection should display correctly in the older version of Mac Os + Safari.
- [ ] Also make sure to check the collection in the older versions of ios + Safari.

**Comment by kevinwhoffman** [comment] 2018-09-11 15:42
Duplicate of #242.

**Closed by kevinwhoffman** 2018-09-11 15:42 UTC
